//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class su
    {
        public int id { get; set; }
        public Nullable<int> faturaId { get; set; }
        public Nullable<int> miiktar { get; set; }
        public Nullable<int> yil { get; set; }
        public Nullable<int> ay { get; set; }
        public Nullable<int> faturaNo { get; set; }
        public Nullable<System.DateTime> sonOdemeTarihi { get; set; }
        public Nullable<int> odenme { get; set; }
    
        public virtual fatura fatura { get; set; }
    }
}
